### ISSUE TITLE
pre-commit not running properly

### ISSUE THREAD

**Issue by newton-per-sqm** [qutech/QuMADA#6]
The existing `.pre-commit-config.yaml` seems to be not working properly in current upstream of main. But the idea of using some pre-commit hooks + isort + black sounds good. Should we refactor the code for a proper running pre-commit configuration? Afterwards we could also include it in the github ci workflow.

Failed checks:
- check docstring
- debug statements
- check python ast
- mixed line ending
- pyupgrade
- black

Maybe we should also reduce the amount of pre-commit checks in the early phase?

**Comment by grothe6** [comment]
Pre-commit works for me on a fresh environment on main. What exactly fails for you?

I do think its a good idea to integrate it into CI to enforce its use.

As not everyone uses pre-commit, running `pre-commit run --all-files` finds lots of issues with the code base. Bringing the whole code base up to par is also a good idea, although a separate issue.

**Comment by newton-per-sqm** [comment]
I'll copy my pre-commit log on a fresh upstream main shortly.

**Comment by newton-per-sqm** [comment]
I think its like you said, more an issue of individually commited files, as not all of us use pre-commit.

Here my log from running `pre-commit run --all`:

´´´log
check docstring is first.................................................Failed
- hook id: check-docstring-first
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Scripts\check-docstring-first.EXE\__main__.py", line 7, in <module>
  File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_docstring_first.py", line 59, in main
    retv |= check_docstring_first(contents, filename=filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_docstring_first.py", line 26, in check_docstring_first        
    for tok_type, _, (sline, scol), _, _ in tok_gen:
  File "C:\Users\MusterPascal\Mambaforge\Lib\tokenize.py", line 516, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 182
    def _add_volt(self):
IndentationError: unindent does not match any outer indentation level

check yaml...............................................................Passed
check json...............................................................Passed
debug statements (python)................................................Failed
- hook id: debug-statements
- exit code: 1

src/qumada/utils/load_save_config.py - Could not parse ast

        Traceback (most recent call last):
          File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\debug_statement_hook.py", line 56, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "src/qumada/utils/load_save_config.py", line 35
            print("No such entry in config:
                  ^
        SyntaxError: unterminated string literal (detected at line 35)


src/qumada/legacy/measurement/measurement_for_immediate_use/SET_testing.py - Could not parse ast

        Traceback (most recent call last):
          File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\debug_statement_hook.py", line 56, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "src/qumada/legacy/measurement/measurement_for_immediate_use/SET_testing.py", line 84
            dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
                                                                                     ^
        SyntaxError: unterminated string literal (detected at line 84)


src/examples/buffered_example1.py - Could not parse ast

        Traceback (most recent call last):
          File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\debug_statement_hook.py", line 56, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "src/examples/buffered_example1.py", line 70
            dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
                                                                                     ^
        SyntaxError: unterminated string literal (detected at line 70)


src/qumada/legacy/measurement/get_from_station.py - Could not parse ast

        Traceback (most recent call last):
          File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\debug_statement_hook.py", line 56, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "src/qumada/legacy/measurement/get_from_station.py", line 200
            key = kwargs.get('key', input('Please enter key to seach for or exit to skip:
                                          ^
        SyntaxError: unterminated string literal (detected at line 200)


src/qumada/legacy/measurement/gate_mapping.py - Could not parse ast

        Traceback (most recent call last):
          File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\debug_statement_hook.py", line 56, in check_file
            ast_obj = ast.parse(f.read(), filename=filename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
            return compile(source, filename, mode, flags,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "src/qumada/legacy/measurement/gate_mapping.py", line 48
            method = input("Do you want to load an existing mapping? (y/n)
                           ^
        SyntaxError: unterminated string literal (detected at line 48)

check python ast.........................................................Failed
- hook id: check-ast
- exit code: 1

src/qumada/utils/load_save_config.py: failed parsing with CPython 3.11.4:

    Traceback (most recent call last):
      File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_ast.py", line 21, in main
        ast.parse(f.read(), filename=filename)
      File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/qumada/utils/load_save_config.py", line 35
        print("No such entry in config:
              ^
    SyntaxError: unterminated string literal (detected at line 35)

src/qumada/legacy/measurement/measurement_for_immediate_use/SET_testing.py: failed parsing with CPython 3.11.4:

    Traceback (most recent call last):
      File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_ast.py", line 21, in main
        ast.parse(f.read(), filename=filename)
      File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/qumada/legacy/measurement/measurement_for_immediate_use/SET_testing.py", line 84
        dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
                                                                                 ^
    SyntaxError: unterminated string literal (detected at line 84)

src/examples/buffered_example1.py: failed parsing with CPython 3.11.4:

    Traceback (most recent call last):
      File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_ast.py", line 21, in main
        ast.parse(f.read(), filename=filename)
      File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/examples/buffered_example1.py", line 70
        dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
                                                                                 ^
    SyntaxError: unterminated string literal (detected at line 70)

src/qumada/legacy/measurement/get_from_station.py: failed parsing with CPython 3.11.4:

    Traceback (most recent call last):
      File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_ast.py", line 21, in main
        ast.parse(f.read(), filename=filename)
      File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/qumada/legacy/measurement/get_from_station.py", line 200
        key = kwargs.get('key', input('Please enter key to seach for or exit to skip:
                                      ^
    SyntaxError: unterminated string literal (detected at line 200)

src/qumada/legacy/measurement/gate_mapping.py: failed parsing with CPython 3.11.4:

    Traceback (most recent call last):
      File "C:\Users\MusterPascal\.cache\pre-commit\repovyrli93l\py_env-default\Lib\site-packages\pre_commit_hooks\check_ast.py", line 21, in main
        ast.parse(f.read(), filename=filename)
      File "C:\Users\MusterPascal\Mambaforge\Lib\ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "src/qumada/legacy/measurement/gate_mapping.py", line 48
        method = input("Do you want to load an existing mapping? (y/n)
                       ^
    SyntaxError: unterminated string literal (detected at line 48)

mixed line ending........................................................Passed
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing src/qumada/legacy/measurement/gate_mapping.py
Fixing src/qumada/instrument/custom_drivers/ZI/MFLI.py
Fixing src/qumada/measurement/measurement.py
Fixing src/qumada/utils/ramp_parameter.py
Fixing src/qumada/utils/load_save_config.py
Fixing src/qumada/legacy/measurement/get_from_station.py
Fixing src/qumada/measurement/scripts/spectrometer.py
Fixing src/tests/plotting_2D.py
Fixing src/qumada/utils/GUI.py
Fixing src/qumada/instrument/mapping/Dummies/DummyDac.py
Fixing src/qumada/utils/load_from_sqlite_db.py
Fixing src/qumada/utils/utils.py
Fixing src/qumada/instrument/mapping/QDevil/qdac.py
Fixing src/qumada/instrument/mapping/Zurich_Instruments/MFLI.json
Fixing src/qumada/instrument/custom_drivers/Harvard/Decadac.py
Fixing src/qumada/instrument/buffers/mfli_buffer.py
Fixing src/qumada/instrument/mapping/Harvard/Decadac.py

fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing src/qumada/measurement/scripts/spectrometer.py
Fixing src/qumada/utils/GUI.py
Fixing src/qumada/utils/utils.py
Fixing docs_requirements.txt
Fixing src/qumada/instrument/mapping/QDevil/qdac.py
Fixing src/qumada/instrument/mapping/QDevil/QDac.json

pyupgrade................................................................Failed
- hook id: pyupgrade
- exit code: 1
- files were modified by this hook

Rewriting src/qumada/measurement/scripts/spectrometer.py
Rewriting src/qumada/utils/load_from_sqlite_db.py
Rewriting src/qumada/utils/parameter_file_helpers.py
Traceback (most recent call last):
  File "C:\Users\MusterPascal\Mambaforge\envs\qumada\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MusterPascal\Mambaforge\envs\qumada\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\MusterPascal\.cache\pre-commit\repoq1txkrok\py_env-default\Scripts\pyupgrade.EXE\__main__.py", line 7, in <module>
  File "C:\Users\MusterPascal\.cache\pre-commit\repoq1txkrok\py_env-default\lib\site-packages\pyupgrade\_main.py", line 381, in main
    ret |= _fix_file(filename, args)
  File "C:\Users\MusterPascal\.cache\pre-commit\repoq1txkrok\py_env-default\lib\site-packages\pyupgrade\_main.py", line 327, in _fix_file
    contents_text = _fix_tokens(contents_text)
  File "C:\Users\MusterPascal\.cache\pre-commit\repoq1txkrok\py_env-default\lib\site-packages\pyupgrade\_main.py", line 281, in _fix_tokens
    tokens = src_to_tokens(contents_text)
  File "C:\Users\MusterPascal\.cache\pre-commit\repoq1txkrok\py_env-default\lib\site-packages\tokenize_rt.py", line 68, in src_to_tokens
    for tok_type, tok_text, (sline, scol), (eline, ecol), line in gen:
  File "C:\Users\MusterPascal\Mambaforge\envs\qumada\lib\tokenize.py", line 512, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 182
    def _add_volt(self):
IndentationError: unindent does not match any outer indentation level

isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\instrument\buffers\mfli_buffer.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\instrument\custom_drivers\Harvard\Decadac.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\instrument\mapping\Harvard\Decadac.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\legacy\measurement\gate_mapping.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\measurement\scripts\__init__.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\measurement\scripts\spectrometer.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\GUI.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\browsefiles.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\load_from_sqlite_db.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\load_save_config.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\parameter_file_helpers.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\qumada\utils\ramp_parameter.py
Fixing C:\Users\MusterPascal\Documents\Repositories\QuMADA\src\tests\plotting_2D.py

black....................................................................Failed
- hook id: black
- exit code: 123
- files were modified by this hook

error: cannot format src\examples\buffered_example1.py: Cannot parse: 70:73: dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
reformatted src\qumada\instrument\buffers\dummy_dmm_buffer.py
reformatted src\qumada\instrument\custom_drivers\Dummies\dummy_dac.py
reformatted src\qumada\instrument\mapping\Dummies\DummyDac.py
reformatted src\qumada\instrument\buffers\mfli_buffer.py
error: cannot format src\qumada\legacy\measurement\gate_mapping.py: Cannot parse: 48:27:             method = input("Do you want to load an existing mapping? (y/n)
reformatted src\qumada\instrument\custom_drivers\Dummies\dummy_dmm.py
reformatted src\qumada\instrument\mapping\QDevil\qdac.py
error: cannot format src\qumada\legacy\measurement\measurement_for_immediate_use\SET_testing.py: Cannot parse: 84:73: dac = Decadac("dac", "ASRL6::INSTR", min_val=-10, max_val=10, terminator="
error: cannot format src\qumada\legacy\measurement\get_from_station.py: Cannot parse: 200:34:     key = kwargs.get('key', input('Please enter key to seach for or exit to skip:    
error: cannot format src\qumada\instrument\mapping\Harvard\Decadac.py: cannot use --safe with this file; failed to parse source file AST: invalid syntax (<unknown>, line 124)     
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
reformatted src\qumada\utils\browsefiles.py
reformatted src\qumada\instrument\custom_drivers\ZI\MFLI.py
reformatted src\qumada\measurement\scripts\spectrometer.py
reformatted src\qumada\utils\import_submodules.py
reformatted src\qumada\utils\GUI.py
reformatted src\qumada\utils\generate_sweeps.py
reformatted src\qumada\utils\init_station.py
error: cannot format src\qumada\utils\load_save_config.py: Cannot parse: 34:10:     print("No such entry in config:
reformatted src\qumada\utils\resources.py
reformatted src\qumada\utils\utils.py
reformatted src\qumada\utils\ramp_parameter.py
reformatted src\qumada\utils\parameter_file_helpers.py
reformatted src\qumada\utils\load_from_sqlite_db.py
reformatted src\qumada\instrument\custom_drivers\Harvard\Decadac.py
reformatted src\tests\plotting_2D.py
reformatted src\qumada\measurement\measurement.py

Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
21 files reformatted, 29 files left unchanged, 6 files failed to reformat.
```

**Comment by newton-per-sqm** [comment]
I've reviewed and worked on some of these files, pre-commit failed afterwards, but not on my changes. I've just stumbled upon this. It would be nice if we could unify our code-base for future developments and new unit tests.

**Comment by grothe6** [comment]
Ok, this is the same output I am getting. This is basically pre-commit working as intended, but our code-base is faulty.

For the normal use of pre-commit, which is checking only the committed files, this is no problem.

**Comment by newton-per-sqm** [comment]
Ok, so when working with pre-commit on some of these files, you would sugggest to also fix up such issues live?

**Comment by grothe6** [comment]
When I work on a file and pre-commit fixes stuff there, I just commit that as well, with a notice on the git commit message.

But I also created a separate issue for refactoring the code base and integrating pre-commit into CI here: #7

**Comment by newton-per-sqm** [comment]
Perfect, thank you. Than whe should merge this here into our new issue #7.

**Comment by newton-per-sqm** [comment]
Perfect, thank you. Than whe should merge this here into our new issue #7.
